pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {

                git url: 'https://github.com/raulblend/web_app.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {

                sh 'pip install -r requirements.txt'
            }
        }
        
        stage('Run Tests') {
            steps {

                sh 'python -m pytest tests/test_redirection.py'
            }
        }
    }

    post {
        always {

            cleanWs()
        }
    }
}
